//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string ProfilePicture { get; set; }
        public string PasswordHash { get; set; }
        public string UserName { get; set; }
        public bool IsActive { get; set; }
    }
}
